/*
   Copyright (c) 2025, Huawei and/or its affiliates. All rights reserved.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License, version 2.0,
   as published by the Free Software Foundation.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License, version 2.0, for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA
*/

#ifndef __CDE_DDL_LOG_H__
#define __CDE_DDL_LOG_H__

#include <stdint.h>

#include "common/dstore_common_utils.h"
#include "tablespace/dstore_tablespace.h"
#include "tablespace/dstore_tablespace_struct.h"

class THD;

namespace CDE {

struct dml_tuple_t;
struct cde_dict_t;
struct session_rel_info;
class cde_session_t;

constexpr DSTORE::TablespaceId CDE_INVALID_SPACE_ID =
    static_cast<DSTORE::TablespaceId>(DSTORE::TBS_ID::INVALID_TABLE_SPACE_ID);
constexpr DSTORE::TablespaceId CDE_DEFAULT_TABLE_SPACE_ID =
    static_cast<DSTORE::TablespaceId>(DSTORE::TBS_ID::DEFAULT_TABLE_SPACE_ID);
constexpr DSTORE::TablespaceId CDE_TMP_TABLE_SPACE_ID =
    static_cast<DSTORE::TablespaceId>(DSTORE::TBS_ID::TEMP_TABLE_SPACE_ID);
constexpr DSTORE::TablespaceId CDE_GLOBAL_TABLE_SPACE_ID =
    static_cast<DSTORE::TablespaceId>(DSTORE::TBS_ID::GLOBAL_TABLE_SPACE_ID);

extern bool g_printDdlLog;
extern int32_t g_ddlLogFillFactorHeap;
extern int32_t g_ddlLogFillFactorIndex;

enum class CdeDdlLogType : uint32_t {
  /** Drop a segment. */
  DROP_SEGMENT_LOG = 1,
  /** Remove dict_table from dict_cache. */
  REMOVE_CACHE_LOG,
  /** Remove in dict_cache. */
  RENAME_TABLE_LOG,
  /** Drop tablespace. */
  DROP_TABLESPACE_LOG,
  /** Most of DDL/DCL/ACL operations don't use any interface of dstore-handler,
  but they require the commit-wal which can be only generated by commiting a
  read-write transaction of dstore to carry DDL-info. By writing a DDL log
  record of this type to create a read-write transactions of dstore.  */
  DUMMY_LOG
};

/** Fields of ddl log table. */
enum class DdlLogField : uint16_t {
  FIELD_ID = 0,
  FIELD_THREAD_ID,
  FIELD_TYPE,
  FIELD_FILE_ID,
  FIELD_BLOCK_ID,
  FIELD_SEGMENT_TYPE,
  FIELD_TABLESPACE_ID,
  FIELD_TABLE_NAME,
  FIELD_TABLE_NAME_NEW,
  FIELD_NUM
};

class CdeDdlLogRecord {
 public:
  /** Log id */
  uint64_t m_id = 0;
  /** Thread ID from thd, which is so called 'Session ID' */
  uint64_t m_threadId;
  /** Log type */
  uint32_t m_type = static_cast<uint32_t>(CdeDdlLogType::DUMMY_LOG);
  /** File ID as part of segment ID. */
  uint16_t m_fileId = DSTORE::INVALID_VFS_FILE_ID;
  /** Block ID as part of segment ID. */
  uint32_t m_blockId = DSTORE::DSTORE_INVALID_BLOCK_NUMBER;
  /** Type of dstore segment. */
  uint8_t m_segmentType =
      static_cast<uint32_t>(DSTORE::SegmentType::HEAP_SEGMENT_TYPE);
  /** TableSpace Id */
  uint16_t m_tableSpaceId = DSTORE::INVALID_TABLESPACE_ID;
  /** Current/old table name. */
  std::string m_tableName;
  /** New table name. */
  std::string m_tableNameNew;
  /** Ctid of this ddl log record in dstore heap. */
  DSTORE::ItemPointerData m_ctid = DSTORE::INVALID_ITEM_POINTER;

  CdeDdlLogRecord(uint64_t threadId) : m_threadId(threadId) {}
  CdeDdlLogRecord(uint64_t threadId, const char *tableName)
      : m_threadId(threadId),
        m_type(static_cast<uint32_t>(CdeDdlLogType::REMOVE_CACHE_LOG)),
        m_tableName(tableName) {}
  CdeDdlLogRecord(uint64_t threadId, const char *oldTableName,
                  const char *tableNameNew)
      : m_threadId(threadId),
        m_type(static_cast<uint32_t>(CdeDdlLogType::RENAME_TABLE_LOG)),
        m_tableName(oldTableName),
        m_tableNameNew(tableNameNew) {}
  CdeDdlLogRecord(uint64_t threadId, uint16_t fileId, uint32_t blockId,
                  uint8_t segmentType, DSTORE::TablespaceId spaceId)
      : m_threadId(threadId),
        m_type(static_cast<uint32_t>(CdeDdlLogType::DROP_SEGMENT_LOG)),
        m_fileId(fileId),
        m_blockId(blockId),
        m_segmentType(segmentType),
        m_tableSpaceId(spaceId) {}
  CdeDdlLogRecord(uint64_t threadId, uint16_t tableSpaceId)
      : m_threadId(threadId),
        m_type(static_cast<uint32_t>(CdeDdlLogType::DROP_TABLESPACE_LOG)),
        m_tableSpaceId(tableSpaceId) {}
  CdeDdlLogRecord(DSTORE::Datum *values, bool *isNulls,
                  DSTORE::ItemPointer ctid);

  /**
  Convert a ddl log record to dstore datums in the tuple.

  @param[in,out]  tuple  Tuple which include dstore datums.
  */
  void RecordToDstoreDatum(dml_tuple_t *tuple) const;

  /**
  Convert a ddl log record to a string.
  */
  std::string ToString() const;

  /**
  Place records by descending order in ordered containers.

  @param[in]  other  Another ddl log record to be compared.
  */
  bool operator<(const CdeDdlLogRecord &other) const {
    return m_id > other.m_id;
  }
};

class CdeDdlLog {
 private:
  /** Dict table of ddl log table. */
  cde_dict_t *m_dictTable = nullptr;
  /** Whether need to skip. */
  bool m_needSkip = true;
  /** Whether in MySQL initialization phase. */
  bool m_isServerInit = false;
  /** Whether should stop backgroup replay thread. */
  bool m_stopFlag = false;
  /** Handler of thread to replay ddl log background. */
  std::thread m_recoverThread;
  /** The max ID of ddl log record for recovery. */
  uint64_t m_recoverMaxId = 0;
  /** Set of ddl log records for recovery, sort by ID in descending order. */
  std::set<CdeDdlLogRecord> m_recoverRecords;
  /** Used to protect m_recoverRecords. Prevent drop tablespace and
   * m_recoverRecords clear. */
  mysql_mutex_t m_recoverRecordsMutex;

  CdeDdlLog() : m_needSkip(true) {
    int32_t ret = MutexInit(0, &m_recoverRecordsMutex, MY_MUTEX_INIT_FAST);
    CDE_ASSERT(ret == 0);
  }
  CdeDdlLog(const CdeDdlLog &) = delete;
  CdeDdlLog &operator=(const CdeDdlLog &) = delete;
  ~CdeDdlLog() {
    int32_t ret = MutexDestroy(&m_recoverRecordsMutex);
    CDE_ASSERT(ret == 0);
  }

  /**
  Get next auto-increment id of ddl log table.
  */
  uint64_t GetNextId();

  /**
  Get ddl log infomation from thd

  @param[in]  thd          Pointer of session descriptor.
  @param[out] threadId     Thread ID from thd, which is so called 'Session ID'.
  @param[out] severXid     Xid from thd, which is so called 'Query ID'.
  */
  void GetDdlLogInfoFromThd(const THD *thd, uint64_t &threadId,
                            uint64_t &severXid);

  /**
  Get or create storage relation of ddl log table.

  @param[in]  thd          Pointer of session descriptor.

  @return ptr of storage relation of ddl log table, nullptr if fail.
  */
  session_rel_info *GetOrCreateRelationInfo(THD *thd);

  /**
  Write ddl logs represent by parameter record into ddl log table.

  @param[in]  thd               Pointer of session descriptor.
  @param[in]  record            DDL log record to be write.
  @param[in]  useAutonomousTrx  Whether the insert operation need to
                                be commited in an autonomous transacion.
  @param[in]  severXid          Xid from thd, just for print log.
  @param[out] writeLogFail      Result to indicate whether write drop
                                segment log failed.

  @return CDE_SUCC if success, CDE_FAIL if fail.
  */
  bool LogRecordToTable(THD *thd, CdeDdlLogRecord &record,
                        bool useAutonomousTrx, uint64_t severXid,
                        bool *writeLogFail = nullptr);

  /**
  Insert a record to ddl log table. This is a inner function of
  LogRecordToTable.

  @param[in]  relationInfo      Dstore storage-relations of ddl log table.
  @param[in]  record            Record to be inserted.
  @param[in]  useAutonomousTrx  Whether the insert operation need to
                                be commited in an autonomous transacion.
  @param[out] dstoreXid         Dstore xid used by writting ddl log table.

  @return CDE_SUCC if success, CDE_FAIL if fail.
  */
  bool WriteRecordToTable(session_rel_info *relationInfo,
                          CdeDdlLogRecord &record, bool useAutonomousTrx,
                          DSTORE::Xid &dstoreXid);

  /**
  Delete a record from ddl log table.

  @param[in]  relationInfo      Dstore storage-relations of ddl log table.
  @param[in]  record            Record to be deleted.

  @return CDE_SUCC if success, CDE_FAIL if fail.
  */
  bool DeleteRecordFromTable(session_rel_info *relationInfo,
                             const CdeDdlLogRecord &record);

  /**
  Search a record from ddl log table with a given thread id.

  @param[in]  threadId         Thread id
  @param[in]  relationInfo     Dstore storage-relations of ddl log table.
  @param[out] records          Records founded from ddl log table
  @return CDE_SUCC if success, CDE_FAIL if fail.
  */
  bool SearchRecordsFromTable(uint64_t threadId, session_rel_info *relationInfo,
                              std::set<CdeDdlLogRecord> &records);

  /**
  Load all records from ddl log table.

  @param[in]  relationInfo      Dstore storage-relations of ddl log table.
  @param[out] records           The set to save ddl log records loaded from
                                table, Sort by ID in descending order.

  @return CDE_SUCC if success, CDE_FAIL if fail.
  */
  void LoadAllRecordsFromTable(session_rel_info &relationInfo);

  /**
  Replay all ddl log records with the same thread ID.

  @param[in]  threadId    Thread ID from thd, which is so called 'Session ID'
  */
  void ReplayByThreadId(THD *thd, uint64_t threadId);

  /**
  Replay a ddl log record.

  @param[in]  record            Record to be replayed.
  @param[in]  relationInfo      Dstore storage-relations of ddl log table.
  @param[in]  isRecovery        Whether in crash-recovery.
  */
  void ReplayRecord(const CdeDdlLogRecord &record,
                    session_rel_info *relationInfo, bool isRecovery);

  /**
  Replay a ddl log record with type DROP_SEGMENT_LOG.

  @param[in]  relationInfo      Dstore storage-relations of ddl log table.
  @param[in]  record            Record to be replayed.
  */
  void ReplayDropSegmentLog(session_rel_info *relationInfo,
                            const CdeDdlLogRecord &record);

  /**
  Replay a ddl log record with type REMOVE_CACHE_LOG.

  @param[in]  record            Record to be replayed.
  @param[in]  isRecovery        Whether in crash-recovery.
  */
  void ReplayRemoveCacheLog(const CdeDdlLogRecord &record, bool isRecovery);

  /**
  Replay a ddl log record with type RENAME_TABLE_LOG.

  @param[in]  record            Record to be replayed.
  @param[in]  isRecovery        Whether in crash-recovery.
  */
  void ReplayRenameTableLog(const CdeDdlLogRecord &record, bool isRecovery);

  /**
  Replay a ddl log record with type DROP_TABLESPACE_LOG.

  @param[in]  relationInfo      Dstore storage-relations of ddl log table.
  @param[in]  record            Record to be replayed.
  */
  void ReplayDropTableSpaceId(session_rel_info *relationInfo,
                              const CdeDdlLogRecord &record);

 public:
  /**
  Get singleton instance of this class.

  @return Pointer of the singleton instance.
  */
  static CdeDdlLog *GetInstance();

  /**
  Create ddl log table. Only print error log if failed.
  */
  void CreateTable();

  /**
  Open ddl log table.

  @return CDE_SUCC if success, CDE_FAIL if fail.
  */
  bool OpenTable();

  /**
  Close ddl log table.
  */
  void CloseTable();

  /**
  Load fill factor from global variables into dictTable object.
  */
  void LoadFillFactor();

  /**
  Set skip flag of ddl log. When it set to true, it is equivalent
  to disable the atomic-ddl feature.

  @param[in]  skip  Value.
  */
  void SetSkip(bool skip);

  void SetServerInit();

  bool IsServerInit();

  /**
  Write a ddl log record with type DROP_SEGMENT_LOG.

  @param[in]  thd           Pointer of session descriptor.
  @param[in]  segmentId     Segment ID.
  @param[in]  segmentType   Segment type.
  @param[in]  spaceId       Tablespace ID.
  @param[in]  isCreate      Flag to indicate the caller is dropping a
                            segment or creating a segment.
  @param[out] writeLogFail  Result to indicate whether write drop segment
                            log failed.

  @return CDE_SUCC if success, CDE_FAIL if fail.
  */
  bool LogDropSegment(THD *thd, const DSTORE::PageId &segmentId,
                      DSTORE::SegmentType segmentType,
                      DSTORE::TablespaceId spaceId, bool isCreate,
                      bool *writeLogFail = nullptr);

  /**
  Write a ddl log record with type RENAME_TABLE_LOG.

  @param[in]  thd           Pointer of session descriptor.
  @param[in]  oldTableName  Original name of the table.
  @param[in]  newTableName  New name of the table.

  @return CDE_SUCC if success, CDE_FAIL if fail.
  */
  bool LogRename(THD *thd, const char *oldTableName, const char *newTableName);

  /**
  Write a ddl log record with type REMOVE_CACHE_LOG.

  @param[in]  thd           Pointer of session descriptor.
  @param[in]  tableName     Name of the table.

  @return CDE_SUCC if success, CDE_FAIL if fail.
  */
  bool LogRemoveCache(THD *thd, const char *tableName);

  /**
  Write a ddl log record with type DUMMY_LOG.

  @param[in]  thd           Pointer of session descriptor.
  @param[in]  session       Pointer of cde session.
  */
  void LogDummy(THD *thd, cde_session_t *session);

  /**
  Write a ddl log record with type DROP_TABLESPACE_LOG.

  @param[in]  thd           Pointer of session descriptor.
  @param[in]  tableSpaceId  TableSpace ID.
  @param[in]  isCreate      Flag whether create tablespace
  @param[out] writeLogFail  Result to indicate whether write create tablespace
  log failed.

  @return CDE_SUCC if success, CDE_FAIL if fail.
  */
  bool LogDropTableSpaceId(THD *thd, const DSTORE::TablespaceId tableSpaceId,
                           bool isCreate, bool *writeLogFail = nullptr);

  /**
  Called after DDL commited/rollbacked to replay ddl logs
  generated by current session.

  @param[in]  thd           Pointer of session descriptor.
  */
  void PostDdl(THD *thd);

  /**
  Interface for post recover of dstore, to replay all ddl logs
  generated at last runtime.
  */
  void ReplayAll();

  /**
  Excution function of background recover thread.
  */
  void ReplayRecordsBackGround();

  /**
  Check whether some recover ddl operations about tablespace exist.

  @param[in]  tableSpaceId  TableSpace ID.

  @return true if find exist record, false if not find.
  */
  bool RemainTablespaceDDL(DSTORE::TablespaceId tableSpaceId);
};

/**
Initialization at startup.

@param[in]  isServerInit   Whether in MySQL initialization.

@return CDE_SUCC if success, CDE_FAIL if fail.
*/
bool CdeDdlLogInit(bool isServerInit);

/**
De-Initialization at shutdown.
*/
void CdeDdlLogDeint();

/**
Whether ddl log is disable for thd.

@param[in]  thd    Pointer of session descriptor.

@return true if disable, otherwise false.
*/
bool CdeIsDdlLogDisable(THD *thd);

/**
Whether current thd is executing a DDL command and with a read write
transacion of Dstore.

@param[in]  thd    Pointer of session descriptor.

@return true if thd is executing a DDL command and with a read write
             transacion of Dstore, otherwise false.
*/
bool CdeIsDdlWithTrx(THD *thd);

inline bool CdeIsDdlLogTableName(const char *name) {
  const char *ddlLogTable = "./mysql/dstore_ddl_log";
  if (strlen(name) == strlen(ddlLogTable) &&
      strncmp(name, ddlLogTable, strlen(ddlLogTable)) == 0) {
    return true;
  }
  return false;
}

}  // namespace CDE
#endif
