#! /bin/bash
# Comments to support chkconfig on RedHat Linux
# chkconfig: - 90 40
# description: A very fast and reliable SQL database engine.

# Comments to support LSB init script conventions
### BEGIN INIT INFO
# Provides: mysql
# Required-Start: $local_fs $network $remote_fs
# Should-Start: ypbind nscd ldap ntpd xntpd
# Required-Stop: $local_fs $network $remote_fs
# Default-Start:  2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop MySQL
# Description: MySQL is a very fast and reliable SQL database engine.
### END INIT INFO

log_success_msg()
{
  echo " SUCCESS! $@"
}
log_failure_msg()
{
  echo " ERROR! $@"
}

if [ $1 == "status" ];then
    chroot_dir="/var/chroot"
    mysqld_pid_file_path="$chroot_dir/tmp/rds_mysql.pid"
    mysql_socket_file_path="$chroot_dir/tmp/mysql.sock"
    if ! test -s "$mysqld_pid_file_path" && test -s $chroot_dir/var/lib/engine/mysqld.pid ; then
      mysqld_pid_file_path="$chroot_dir/var/lib/engine/mysqld.pid"
    fi
    lock_file_path="$chroot_dir/var/lock/subsys/mysql"
    # First, check to see if pid file exists
    if test -s "$mysqld_pid_file_path" ; then 
      read mysqld_pid < "$mysqld_pid_file_path"
      if kill -0 $mysqld_pid 2>/dev/null ; then 
        if ! test -e "$mysql_socket_file_path" ; then 
          log_failure_msg "MySQL is running, but socket file could not be found"
          exit 6
        fi
        log_success_msg "MySQL running ($mysqld_pid)"
        exit 0
      else
        log_failure_msg "MySQL is not running, but PID file exists"
        exit 1
      fi
    else
      # Try to find appropriate mysqld process
      mysqld_pid=`pidof /usr/local/engine/bin/mysqld`

      # test if multiple pids exist
      pid_count=`echo $mysqld_pid | wc -w`
      if test $pid_count -gt 1 ; then
        log_failure_msg "Multiple MySQL running but PID file could not be found ($mysqld_pid)"
        exit 5
      elif test -z $mysqld_pid ; then 
        if test -f "$lock_file_path" ; then 
          log_failure_msg "MySQL is not running, but lock file ($lock_file_path) exists"
          exit 2
        fi 
        log_failure_msg "MySQL is not running"
        exit 3
      else
        log_failure_msg "MySQL is running but PID file could not be found"
        exit 4
      fi
    fi
else
    result=`sudo systemctl $1 mysqld.service`
fi
